//
//  Texts.swift
import Foundation

struct Texts {
 
    //FAQ texts
    static let howToOneDevice = "If you are running with one device, your device will be your end gate. This means you have to set up your device at the finish line of your run. The camera and the sensor area (the orange target) should point at where you will cross the finish line. Try pointing the sensor where you expect your pelvis to cross the finish line. When you start the count down, make sure you have selected enough time so that you can walk back to the starting line and get ready before the run begins.\n"
    static let howToTwoDevices = "If you are running with two devices, one device will be your starting gate and one will be your end gate. If the camera is on on your starting gate, set up the gate so the camera and the sensor area (the orange target) are pointing at where you will cross the start line.\n\nPlace your end gate at the finish line of your run. The camera and the sensor area should point at where you will cross the finish line. Try pointing the sensor where you expect your pelvis to cross the finish line."
    static let reactionRun = "A reaction run is designed to help you practice your reaction skills. In a “reaction run” the start signal goes off at a random time during the selected reaction period. If you select a reaction period of 5 seconds, the app will count down to 0 in the usual way, and then the start signal will go off at some random time between countdown and the following 5 seconds. The element of surprise means you must be ready to react at any time!\n\nIf you are running with two gates, the first gate will register how fast or slow your reaction is. So, make sure to set up the first gate at your starting line if you want to know your reaction time."
    static let flyingStart = "A flying start run is designed to help you measure top speed or your speed between the two gates. In a flying start, you should already be running at top speed before you cross the first gate. You may for example do a flying start run where there is a distance of 5 meters or yards between the first and second gate. You will want to start your run about 20 meters or yards ahead of the first gate, in order to gain full speed before crossing the gates. The app will calculate the time you used based on the time it took to run from the first gate to the last."
    static let addSecondGate = "To add a second running gate you will need 2 devices. You can use 2 devices of your own, or you can connect with a friend who also has the app.\n\nStart by clicking on the “2 Gates” button  or the “QR code” button on the home page. This will open a new screen where you have access to your personal QR-code and to a QR-scanner. Complete the same steps with the second device. Use one of the devices to scan the QR-code of the other device. When the QR-code is detected, the devices should connect automatically.\n\nOne device will be the first gate and this is the device that determines the run set up. The other device will be the second gate and has limited features other than preparing the second gate."
    static let didntRegister = "Make sure that the sensor area (the orange circle shown on the start and end gate) is pointed in a way so the camera will capture your body as you run past the gates. If the problem persists, try to make the sensor more sensitive. You can do this by clicking on the sensor and dragging the sensitivity slider towards the right. "
    static let tooManyRegisters = "If this happens, your sensor might be too sensitive. You can make the sensor less sensitive by clicking on the sensor and dragging the sensitivity slider towards the right."
    static let falseStart = "When you set “false start” to “yes” it means that the app will try to detect whether you start your run too early. If you pass the sensor before the start signal has sounded, you will hear a disqualifying warning sound and your run will be terminated."
    static let cantHearCountDown = "If you have trouble hearing the countdown you can: \n1. Use airpods or similar.\n2. Connect to a speaker\n3. Connect to a second gate. This way the count down is at the starting gate and easier to hear."
    
    // About texts

}
